import { test, expect } from '@playwright/test';
import { setTimeout } from 'node:timers/promises';

test('test', async ({ page }) => {
  await page.goto('http://a31ab0521b7614fc494b75314e386461-307954604.ap-southeast-1.elb.amazonaws.com:7007/');
  const page1Promise = page.waitForEvent('popup');
  await page.locator('li').filter({ hasText: 'LoginSign in using Open ID' }).getByRole('button').click();
  const page1 = await page1Promise;
  await page1.getByLabel('Username or email').click();
  await page1.getByLabel('Username or email').fill('catalog-user');
  await page1.getByLabel('Password', { exact: true }).click();
  await page1.getByLabel('Password', { exact: true }).fill('flowsource1');
  await page1.getByLabel('Show password').click();
  await page1.getByRole('button', { name: 'Sign In' }).click();
  await page.goto('http://a31ab0521b7614fc494b75314e386461-307954604.ap-southeast-1.elb.amazonaws.com:7007/catalog?filters%5Bkind%5D=component');
  await page.getByPlaceholder('Filter').click();
  await page.getByPlaceholder('Filter').fill('auto');
  await page.getByRole('link', { name: 'TicketBookingAutomation' }).click();
  await page.getByTestId('header-tab-2').click();
  //await expect(page.getByRole('heading', { name: 'TheCognizantFoundry/' })).toBeVisible();
  //await expect(page.getByPlaceholder('Search')).toBeVisible();
  //await expect(page.getByRole('link', { name: 'Prisma changes in catalog info' })).toBeVisible();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Unified app' }).click();
  const page2 = await page2Promise;
  await page2.close();
  await setTimeout(3000);
  //await expect(page.getByRole('link', { name: 'Unified app' })).toBeVisible();
  await page.getByRole('button', { name: 'OPEN' }).click();
  await page.getByRole('button', { name: 'CLOSED' }).click();
  await setTimeout(3000);
  await page.getByRole('button', { name: 'ALL' }).click();
  await setTimeout(3000);
  await page.getByRole('button', { name: 'OPEN' }).click();
  await setTimeout(3000);
  await page.getByRole('button', { name: 'CLOSED' }).click();
  await page.getByPlaceholder('Search').click();
  await setTimeout(2000);
  await page.getByPlaceholder('Search').fill('jenkin');
  await setTimeout(2000);

  await page.getByRole('article').getByRole('img').nth(2).click();
  await page.getByRole('article').locator('path').nth(1).click();
  await setTimeout(2000);

  await expect(page.getByRole('link', { name: 'Workflow integration' })).toBeVisible();
  await expect(page.getByRole('link', { name: '2', exact: true })).toBeVisible();
  await page.getByLabel('Next').click();
  await setTimeout(2000);
  await expect(page.getByRole('link', { name: '1' })).toBeVisible();
  await setTimeout(2000);
  await page.getByRole('link', { name: '1' }).click();
});