import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://a31ab0521b7614fc494b75314e386461-307954604.ap-southeast-1.elb.amazonaws.com:7007/');
  const page1Promise = page.waitForEvent('popup');
  await page.locator('li').filter({ hasText: 'LoginSign in using Open ID' }).getByRole('button').click();
  const page1 = await page1Promise;
  await page1.getByLabel('Username or email').click();
  await page1.getByLabel('Username or email').fill('catalog-user');
  await page1.getByLabel('Password', { exact: true }).click();
  await page1.getByLabel('Password', { exact: true }).fill('flowsource1');
  await page1.getByRole('button', { name: 'Sign In' }).click();
  await page.goto('http://a31ab0521b7614fc494b75314e386461-307954604.ap-southeast-1.elb.amazonaws.com:7007/catalog?filters%5Bkind%5D=component');
  await page.getByPlaceholder('Filter').click();
  await page.getByPlaceholder('Filter').fill('jira');
  await page.getByRole('link', { name: 'Jira' }).click();
  await page.getByTestId('header-tab-1').click();
  await expect(page.locator('canvas').first()).toBeVisible();
  await expect(page.locator('canvas').nth(1)).toBeVisible();
  await expect(page.getByRole('link', { name: 'UPSHIFT-3191' })).toBeVisible();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'UPSHIFT-3191' }).click();
  const page2 = await page2Promise;
  await page.waitForTimeout(3000);
  await page2.close();

  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'UPSHIFT-3190' }).click();
  const page3 = await page3Promise;
  await page.waitForTimeout(3000);
  await page3.close();
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'UPSHIFT-3189' }).click();
  const page4 = await page4Promise;
  await page.waitForTimeout(3000);
  await page4.close();
  await page.getByRole('cell', { name: 'Testing for Flowsource' }).click();
  await expect(page.getByRole('cell', { name: 'As a user, I want to be able to enter my personal information (name, email,' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Jira project name: UPSHIFT' })).toBeVisible();
});